name: Linux Release
permissions:
  contents: write

on:
  push:
    tags:
      - '*'
      - '!*-alpha*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 16

      - name: 构建前端
        env:
          CI: ""
        run: |
          cd web
          npm install
          VITE_REACT_APP_VERSION=$(git describe --tags) REACT_APP_VERSION=$(git describe --tags) npm run build
          cd ..

      - name: 设置 Go 环境
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.18.0'

      - name: 安装依赖（仅 arm64）
        if: matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu

      - name: 构建后端
        env:
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
        run: |
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            export CC=aarch64-linux-gnu-gcc
          fi
          go mod download
          CGO_ENABLED=1 go build -ldflags "-s -w -X 'one-api/common.Version=$(git describe --tags)' -extldflags '-static'" -trimpath -o one-api-${{ matrix.arch }}

      - name: 发布
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: one-api-*
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}